// types/supabase.ts
// Generated by Supabase MCP `supabase__generate_typescript_types` (story 4.6).
// Regeneration : lancer le MCP puis copier integralement le retour ici.
// Verification : `npm run check:types:supabase` (presence + validite, pas de regeneration auto).
// Derniere regeneration : story 6.A.3 (2026-05-13) apres migration 6.A.2.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      accompagnants_profiles: {
        Row: {
          adresse: string | null
          code_postal: string | null
          created_at: string
          description: string | null
          diplomes: string[] | null
          disponibilites: Json | null
          disponible: boolean
          experience: string | null
          id: string
          indisponible_jusqu_au: string | null
          justificatif_cv_url: string | null
          justificatif_diplome_url: string | null
          justificatif_identite_url: string | null
          justificatif_permis_url: string | null
          justificatifs_autres: string[] | null
          justificatifs_diplomes: Json | null
          langues: string[] | null
          latitude: number | null
          longitude: number | null
          permis_conduire: boolean | null
          rayon_km: number | null
          refus_motif: string | null
          specialites: string[] | null
          updated_at: string
          user_id: string
          validated_by: string | null
          validation_date: string | null
          validation_source: string
          validation_status: Database["public"]["Enums"]["validation_status"]
          vehicule: boolean | null
          ville: string | null
          visio_date: string | null
          visio_notes: string | null
        }
        Insert: {
          adresse?: string | null
          code_postal?: string | null
          created_at?: string
          description?: string | null
          diplomes?: string[] | null
          disponibilites?: Json | null
          disponible?: boolean
          experience?: string | null
          id?: string
          indisponible_jusqu_au?: string | null
          justificatif_cv_url?: string | null
          justificatif_diplome_url?: string | null
          justificatif_identite_url?: string | null
          justificatif_permis_url?: string | null
          justificatifs_autres?: string[] | null
          justificatifs_diplomes?: Json | null
          langues?: string[] | null
          latitude?: number | null
          longitude?: number | null
          permis_conduire?: boolean | null
          rayon_km?: number | null
          refus_motif?: string | null
          specialites?: string[] | null
          updated_at?: string
          user_id: string
          validated_by?: string | null
          validation_date?: string | null
          validation_source?: string
          validation_status?: Database["public"]["Enums"]["validation_status"]
          vehicule?: boolean | null
          ville?: string | null
          visio_date?: string | null
          visio_notes?: string | null
        }
        Update: {
          adresse?: string | null
          code_postal?: string | null
          created_at?: string
          description?: string | null
          diplomes?: string[] | null
          disponibilites?: Json | null
          disponible?: boolean
          experience?: string | null
          id?: string
          indisponible_jusqu_au?: string | null
          justificatif_cv_url?: string | null
          justificatif_diplome_url?: string | null
          justificatif_identite_url?: string | null
          justificatif_permis_url?: string | null
          justificatifs_autres?: string[] | null
          justificatifs_diplomes?: Json | null
          langues?: string[] | null
          latitude?: number | null
          longitude?: number | null
          permis_conduire?: boolean | null
          rayon_km?: number | null
          refus_motif?: string | null
          specialites?: string[] | null
          updated_at?: string
          user_id?: string
          validated_by?: string | null
          validation_date?: string | null
          validation_source?: string
          validation_status?: Database["public"]["Enums"]["validation_status"]
          vehicule?: boolean | null
          ville?: string | null
          visio_date?: string | null
          visio_notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "accompagnants_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "accompagnants_profiles_validated_by_fkey"
            columns: ["validated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      accompagne_accompagnants: {
        Row: {
          accompagnant_user_id: string
          accompagne_id: string
          actif: boolean
          couleur: string
          created_at: string
          id: string
        }
        Insert: {
          accompagnant_user_id: string
          accompagne_id: string
          actif?: boolean
          couleur?: string
          created_at?: string
          id?: string
        }
        Update: {
          accompagnant_user_id?: string
          accompagne_id?: string
          actif?: boolean
          couleur?: string
          created_at?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "accompagne_accompagnants_accompagnant_user_id_fkey"
            columns: ["accompagnant_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "accompagne_accompagnants_accompagne_id_fkey"
            columns: ["accompagne_id"]
            isOneToOne: false
            referencedRelation: "accompagnes_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      accompagnes_profiles: {
        Row: {
          adresse: string | null
          code_postal: string | null
          created_at: string
          id: string
          updated_at: string
          user_id: string
          ville: string | null
        }
        Insert: {
          adresse?: string | null
          code_postal?: string | null
          created_at?: string
          id?: string
          updated_at?: string
          user_id: string
          ville?: string | null
        }
        Update: {
          adresse?: string | null
          code_postal?: string | null
          created_at?: string
          id?: string
          updated_at?: string
          user_id?: string
          ville?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "beneficiaires_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_actions_log: {
        Row: {
          action_type: string
          admin_id: string | null
          created_at: string
          details: Json | null
          id: string
          target_id: string
          target_id_text: string | null
          target_type: string
        }
        Insert: {
          action_type: string
          admin_id?: string | null
          created_at?: string
          details?: Json | null
          id?: string
          target_id: string
          target_id_text?: string | null
          target_type: string
        }
        Update: {
          action_type?: string
          admin_id?: string | null
          created_at?: string
          details?: Json | null
          id?: string
          target_id?: string
          target_id_text?: string | null
          target_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_actions_log_admin_id_fkey"
            columns: ["admin_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      annonces_accompagnants: {
        Row: {
          accompagnant_id: string
          code_postal: string | null
          contacts_count: number
          created_at: string
          description: string | null
          disponibilites: Json | null
          favoris_count: number
          id: string
          published_at: string | null
          rayon_km: number | null
          status: Database["public"]["Enums"]["annonce_status"]
          titre: string
          updated_at: string
          ville: string | null
          vues: number
        }
        Insert: {
          accompagnant_id: string
          code_postal?: string | null
          contacts_count?: number
          created_at?: string
          description?: string | null
          disponibilites?: Json | null
          favoris_count?: number
          id?: string
          published_at?: string | null
          rayon_km?: number | null
          status?: Database["public"]["Enums"]["annonce_status"]
          titre: string
          updated_at?: string
          ville?: string | null
          vues?: number
        }
        Update: {
          accompagnant_id?: string
          code_postal?: string | null
          contacts_count?: number
          created_at?: string
          description?: string | null
          disponibilites?: Json | null
          favoris_count?: number
          id?: string
          published_at?: string | null
          rayon_km?: number | null
          status?: Database["public"]["Enums"]["annonce_status"]
          titre?: string
          updated_at?: string
          ville?: string | null
          vues?: number
        }
        Relationships: [
          {
            foreignKeyName: "annonces_accompagnants_accompagnant_id_fkey"
            columns: ["accompagnant_id"]
            isOneToOne: false
            referencedRelation: "accompagnants_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      annonces_accompagnes: {
        Row: {
          accompagne_id: string
          besoins_specifiques: string | null
          code_postal: string | null
          created_at: string
          date_debut: string | null
          description: string | null
          diplome_requis: string | null
          disponibilites: Json | null
          equipe_en_place: string | null
          experience_min: string | null
          id: string
          infos_complementaires: string | null
          latitude: number | null
          longitude: number | null
          message_accompagnants: string | null
          niveau_dependance:
            | Database["public"]["Enums"]["niveau_dependance"]
            | null
          ouverture_aide: string | null
          published_at: string | null
          specialites_recherchees: string[] | null
          status: Database["public"]["Enums"]["annonce_status"]
          titre: string
          updated_at: string
          ville: string | null
        }
        Insert: {
          accompagne_id: string
          besoins_specifiques?: string | null
          code_postal?: string | null
          created_at?: string
          date_debut?: string | null
          description?: string | null
          diplome_requis?: string | null
          disponibilites?: Json | null
          equipe_en_place?: string | null
          experience_min?: string | null
          id?: string
          infos_complementaires?: string | null
          latitude?: number | null
          longitude?: number | null
          message_accompagnants?: string | null
          niveau_dependance?:
            | Database["public"]["Enums"]["niveau_dependance"]
            | null
          ouverture_aide?: string | null
          published_at?: string | null
          specialites_recherchees?: string[] | null
          status?: Database["public"]["Enums"]["annonce_status"]
          titre: string
          updated_at?: string
          ville?: string | null
        }
        Update: {
          accompagne_id?: string
          besoins_specifiques?: string | null
          code_postal?: string | null
          created_at?: string
          date_debut?: string | null
          description?: string | null
          diplome_requis?: string | null
          disponibilites?: Json | null
          equipe_en_place?: string | null
          experience_min?: string | null
          id?: string
          infos_complementaires?: string | null
          latitude?: number | null
          longitude?: number | null
          message_accompagnants?: string | null
          niveau_dependance?:
            | Database["public"]["Enums"]["niveau_dependance"]
            | null
          ouverture_aide?: string | null
          published_at?: string | null
          specialites_recherchees?: string[] | null
          status?: Database["public"]["Enums"]["annonce_status"]
          titre?: string
          updated_at?: string
          ville?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "annonces_beneficiaires_beneficiaire_id_fkey"
            columns: ["accompagne_id"]
            isOneToOne: false
            referencedRelation: "accompagnes_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      badges_cache: {
        Row: {
          actif: boolean
          anciennete: string | null
          disponible: boolean
          id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          actif?: boolean
          anciennete?: string | null
          disponible?: boolean
          id?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          actif?: boolean
          anciennete?: string | null
          disponible?: boolean
          id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "badges_cache_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          accompagnant_id: string
          accompagne_id: string | null
          admin_id: string | null
          archived_by_accompagnant: boolean
          archived_by_accompagne: boolean
          created_at: string
          id: string
          last_message_at: string | null
        }
        Insert: {
          accompagnant_id: string
          accompagne_id?: string | null
          admin_id?: string | null
          archived_by_accompagnant?: boolean
          archived_by_accompagne?: boolean
          created_at?: string
          id?: string
          last_message_at?: string | null
        }
        Update: {
          accompagnant_id?: string
          accompagne_id?: string | null
          admin_id?: string | null
          archived_by_accompagnant?: boolean
          archived_by_accompagne?: boolean
          created_at?: string
          id?: string
          last_message_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_accompagnant_id_fkey"
            columns: ["accompagnant_id"]
            isOneToOne: false
            referencedRelation: "accompagnants_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_admin_id_fkey"
            columns: ["admin_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_beneficiaire_id_fkey"
            columns: ["accompagne_id"]
            isOneToOne: false
            referencedRelation: "accompagnes_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      departements_ouverts: {
        Row: {
          code: string
          nom: string
          ouvert: boolean
          ouvert_le: string | null
          region: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          code: string
          nom: string
          ouvert?: boolean
          ouvert_le?: string | null
          region: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          code?: string
          nom?: string
          ouvert?: boolean
          ouvert_le?: string | null
          region?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "departements_ouverts_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      favoris: {
        Row: {
          annonce_accompagnant_id: string | null
          annonce_accompagne_id: string | null
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          annonce_accompagnant_id?: string | null
          annonce_accompagne_id?: string | null
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          annonce_accompagnant_id?: string | null
          annonce_accompagne_id?: string | null
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favoris_annonce_accompagnant_id_fkey"
            columns: ["annonce_accompagnant_id"]
            isOneToOne: false
            referencedRelation: "annonces_accompagnants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favoris_annonce_beneficiaire_id_fkey"
            columns: ["annonce_accompagne_id"]
            isOneToOne: false
            referencedRelation: "annonces_accompagnes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favoris_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          content: string
          conversation_id: string
          created_at: string
          id: string
          read_at: string | null
          sender_id: string
        }
        Insert: {
          content: string
          conversation_id: string
          created_at?: string
          id?: string
          read_at?: string | null
          sender_id: string
        }
        Update: {
          content?: string
          conversation_id?: string
          created_at?: string
          id?: string
          read_at?: string | null
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications_log: {
        Row: {
          created_at: string
          data: Json | null
          email: string | null
          error: string | null
          id: string
          sent_at: string | null
          status: string
          subject: string | null
          template: string | null
          type: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          data?: Json | null
          email?: string | null
          error?: string | null
          id?: string
          sent_at?: string | null
          status?: string
          subject?: string | null
          template?: string | null
          type: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          data?: Json | null
          email?: string | null
          error?: string | null
          id?: string
          sent_at?: string | null
          status?: string
          subject?: string | null
          template?: string | null
          type?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications_ouverture: {
        Row: {
          code_departement: string
          created_at: string
          email: string
          id: string
          ip_inscription: string | null
          notified_at: string | null
          role: string | null
          user_agent: string | null
        }
        Insert: {
          code_departement: string
          created_at?: string
          email: string
          id?: string
          ip_inscription?: string | null
          notified_at?: string | null
          role?: string | null
          user_agent?: string | null
        }
        Update: {
          code_departement?: string
          created_at?: string
          email?: string
          id?: string
          ip_inscription?: string | null
          notified_at?: string | null
          role?: string | null
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "waitlist_departements_code_departement_fkey"
            columns: ["code_departement"]
            isOneToOne: false
            referencedRelation: "departements_ouverts"
            referencedColumns: ["code"]
          },
        ]
      }
      parrainages: {
        Row: {
          blocage_raison: string | null
          code: string
          confirme_at: string | null
          created_at: string | null
          expire_at: string | null
          filleule_abonnee_at: string | null
          filleule_id: string | null
          filleule_inscrite_at: string | null
          flag_suspicion: string | null
          id: string
          ip_inscription: string | null
          marraine_id: string | null
          statut: string
          stripe_fingerprint: string | null
        }
        Insert: {
          blocage_raison?: string | null
          code: string
          confirme_at?: string | null
          created_at?: string | null
          expire_at?: string | null
          filleule_abonnee_at?: string | null
          filleule_id?: string | null
          filleule_inscrite_at?: string | null
          flag_suspicion?: string | null
          id?: string
          ip_inscription?: string | null
          marraine_id?: string | null
          statut?: string
          stripe_fingerprint?: string | null
        }
        Update: {
          blocage_raison?: string | null
          code?: string
          confirme_at?: string | null
          created_at?: string | null
          expire_at?: string | null
          filleule_abonnee_at?: string | null
          filleule_id?: string | null
          filleule_inscrite_at?: string | null
          flag_suspicion?: string | null
          id?: string
          ip_inscription?: string | null
          marraine_id?: string | null
          statut?: string
          stripe_fingerprint?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "parrainages_filleule_id_fkey"
            columns: ["filleule_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parrainages_marraine_id_fkey"
            columns: ["marraine_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      parrainages_codes: {
        Row: {
          code: string
          compteur_confirmes: number
          created_at: string | null
          derniere_recompense_at: string | null
          total_recompenses: number
          user_id: string
        }
        Insert: {
          code: string
          compteur_confirmes?: number
          created_at?: string | null
          derniere_recompense_at?: string | null
          total_recompenses?: number
          user_id: string
        }
        Update: {
          code?: string
          compteur_confirmes?: number
          created_at?: string | null
          derniere_recompense_at?: string | null
          total_recompenses?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "parrainages_codes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      planning_document_assignments: {
        Row: {
          accompagnant_user_id: string
          created_at: string
          document_id: string
          id: string
        }
        Insert: {
          accompagnant_user_id: string
          created_at?: string
          document_id: string
          id?: string
        }
        Update: {
          accompagnant_user_id?: string
          created_at?: string
          document_id?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "planning_document_assignments_auxiliaire_user_id_fkey"
            columns: ["accompagnant_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "planning_document_assignments_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "planning_documents"
            referencedColumns: ["id"]
          },
        ]
      }
      planning_document_reads: {
        Row: {
          document_id: string
          id: string
          read_at: string
          user_id: string
        }
        Insert: {
          document_id: string
          id?: string
          read_at?: string
          user_id: string
        }
        Update: {
          document_id?: string
          id?: string
          read_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "planning_document_reads_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "planning_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "planning_document_reads_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      planning_documents: {
        Row: {
          accompagne_id: string
          created_at: string
          file_path: string
          file_size: number
          id: string
          mime_type: string | null
          nom_fichier: string
        }
        Insert: {
          accompagne_id: string
          created_at?: string
          file_path: string
          file_size?: number
          id?: string
          mime_type?: string | null
          nom_fichier: string
        }
        Update: {
          accompagne_id?: string
          created_at?: string
          file_path?: string
          file_size?: number
          id?: string
          mime_type?: string | null
          nom_fichier?: string
        }
        Relationships: [
          {
            foreignKeyName: "planning_documents_beneficiaire_id_fkey"
            columns: ["accompagne_id"]
            isOneToOne: false
            referencedRelation: "accompagnes_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      planning_shifts: {
        Row: {
          accompagnant_user_id: string
          accompagne_id: string
          created_at: string
          creneaux: Json
          date: string
          id: string
          note: string | null
          total_heures: number
          updated_at: string
        }
        Insert: {
          accompagnant_user_id: string
          accompagne_id: string
          created_at?: string
          creneaux?: Json
          date: string
          id?: string
          note?: string | null
          total_heures?: number
          updated_at?: string
        }
        Update: {
          accompagnant_user_id?: string
          accompagne_id?: string
          created_at?: string
          creneaux?: Json
          date?: string
          id?: string
          note?: string | null
          total_heures?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "planning_shifts_auxiliaire_user_id_fkey"
            columns: ["accompagnant_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "planning_shifts_beneficiaire_id_fkey"
            columns: ["accompagne_id"]
            isOneToOne: false
            referencedRelation: "accompagnes_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      planning_subscriptions: {
        Row: {
          cancel_at: string | null
          cancelled_at: string | null
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          first_subscription_date: string | null
          id: string
          plan_type: string | null
          status: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id: string | null
          stripe_price_id: string | null
          stripe_subscription_id: string | null
          trial_end: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          cancel_at?: string | null
          cancelled_at?: string | null
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          first_subscription_date?: string | null
          id?: string
          plan_type?: string | null
          status?: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id?: string | null
          stripe_price_id?: string | null
          stripe_subscription_id?: string | null
          trial_end?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          cancel_at?: string | null
          cancelled_at?: string | null
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          first_subscription_date?: string | null
          id?: string
          plan_type?: string | null
          status?: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id?: string | null
          stripe_price_id?: string | null
          stripe_subscription_id?: string | null
          trial_end?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "planning_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      rate_limit_tracker: {
        Row: {
          count: number
          key: string
          window_start: string
        }
        Insert: {
          count?: number
          key: string
          window_start?: string
        }
        Update: {
          count?: number
          key?: string
          window_start?: string
        }
        Relationships: []
      }
      signalements: {
        Row: {
          auteur_id: string
          cible_id: string
          cible_type: string
          created_at: string
          decision: string | null
          description: string | null
          id: string
          motif: string
          notes_admin: string | null
          status: string
          traite_at: string | null
          traite_par: string | null
        }
        Insert: {
          auteur_id: string
          cible_id: string
          cible_type: string
          created_at?: string
          decision?: string | null
          description?: string | null
          id?: string
          motif: string
          notes_admin?: string | null
          status?: string
          traite_at?: string | null
          traite_par?: string | null
        }
        Update: {
          auteur_id?: string
          cible_id?: string
          cible_type?: string
          created_at?: string
          decision?: string | null
          description?: string | null
          id?: string
          motif?: string
          notes_admin?: string | null
          status?: string
          traite_at?: string | null
          traite_par?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "signalements_auteur_id_fkey"
            columns: ["auteur_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "signalements_traite_par_fkey"
            columns: ["traite_par"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      stripe_events_processed: {
        Row: {
          event_id: string
          event_type: string
          processed_at: string
        }
        Insert: {
          event_id: string
          event_type: string
          processed_at?: string
        }
        Update: {
          event_id?: string
          event_type?: string
          processed_at?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          cancel_at: string | null
          cancel_comment: string | null
          cancel_feedback: string | null
          cancelled_at: string | null
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          first_subscription_date: string | null
          id: string
          plan_type: string | null
          status: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id: string | null
          stripe_price_id: string | null
          stripe_subscription_id: string | null
          trial_end: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          cancel_at?: string | null
          cancel_comment?: string | null
          cancel_feedback?: string | null
          cancelled_at?: string | null
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          first_subscription_date?: string | null
          id?: string
          plan_type?: string | null
          status?: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id?: string | null
          stripe_price_id?: string | null
          stripe_subscription_id?: string | null
          trial_end?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          cancel_at?: string | null
          cancel_comment?: string | null
          cancel_feedback?: string | null
          cancelled_at?: string | null
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          first_subscription_date?: string | null
          id?: string
          plan_type?: string | null
          status?: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id?: string | null
          stripe_price_id?: string | null
          stripe_subscription_id?: string | null
          trial_end?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string
          first_name: string
          id: string
          last_name: string
          last_seen_at: string | null
          parrainee_par: string | null
          phone: string | null
          phone_hash: string | null
          rappels_optout: boolean
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email: string
          first_name: string
          id: string
          last_name: string
          last_seen_at?: string | null
          parrainee_par?: string | null
          phone?: string | null
          phone_hash?: string | null
          rappels_optout?: boolean
          role: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string
          first_name?: string
          id?: string
          last_name?: string
          last_seen_at?: string | null
          parrainee_par?: string | null
          phone?: string | null
          phone_hash?: string | null
          rappels_optout?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_parrainee_par_fkey"
            columns: ["parrainee_par"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      parrainages_filleule_view: {
        Row: {
          filleule_id: string | null
          id: string | null
          statut: string | null
        }
        Insert: {
          filleule_id?: string | null
          id?: string | null
          statut?: string | null
        }
        Update: {
          filleule_id?: string | null
          id?: string | null
          statut?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "parrainages_filleule_id_fkey"
            columns: ["filleule_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      generate_unique_parrainage_code: { Args: never; Returns: string }
      has_active_subscription: { Args: never; Returns: boolean }
      is_accompagnant: { Args: never; Returns: boolean }
      is_accompagne: { Args: never; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      is_document_owner: { Args: { doc_id: string }; Returns: boolean }
      merge_parrainage_flag_suspicion: {
        Args: { p_flag: string; p_parrainage_id: string }
        Returns: {
          flag_suspicion: string
          id: string
          was_added: boolean
        }[]
      }
      parrainage_claim_recompense: {
        Args: { p_marraine_id: string; p_palier: number }
        Returns: {
          claimed: boolean
          total_recompenses: number
        }[]
      }
      parrainage_increment_compteur: {
        Args: { p_marraine_id: string }
        Returns: number
      }
      parrainage_rollback_recompense: {
        Args: {
          p_expected_total: number
          p_marraine_id: string
          p_palier: number
        }
        Returns: boolean
      }
      try_consume_rate_limit: {
        Args: {
          p_key: string
          p_max_requests: number
          p_window_seconds: number
        }
        Returns: boolean
      }
    }
    Enums: {
      annonce_status: "brouillon" | "publiee" | "archivee" | "suspendue"
      creneau_horaire: "matin" | "apres_midi" | "soir" | "nuit"
      jour_semaine:
        | "lundi"
        | "mardi"
        | "mercredi"
        | "jeudi"
        | "vendredi"
        | "samedi"
        | "dimanche"
      niveau_dependance:
        | "besoins_plus_plus_plus"
        | "besoins_plus_plus"
        | "besoins_plus"
      subscription_status: "active" | "cancelled" | "past_due" | "trialing"
      user_role: "accompagnant" | "accompagne" | "admin"
      validation_status:
        | "en_attente"
        | "visio_a_planifier"
        | "visio_realisee"
        | "valide"
        | "refuse"
        | "a_completer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      annonce_status: ["brouillon", "publiee", "archivee", "suspendue"],
      creneau_horaire: ["matin", "apres_midi", "soir", "nuit"],
      jour_semaine: [
        "lundi",
        "mardi",
        "mercredi",
        "jeudi",
        "vendredi",
        "samedi",
        "dimanche",
      ],
      niveau_dependance: [
        "besoins_plus_plus_plus",
        "besoins_plus_plus",
        "besoins_plus",
      ],
      subscription_status: ["active", "cancelled", "past_due", "trialing"],
      user_role: ["accompagnant", "accompagne", "admin"],
      validation_status: [
        "en_attente",
        "visio_a_planifier",
        "visio_realisee",
        "valide",
        "refuse",
        "a_completer",
      ],
    },
  },
} as const
